version: "3.9"
 
services:

  priya:

    image: redis:7

    container_name: redisserver

    networks:

      - redis-net
 
  client:

    image: redis:7

    container_name: redisclient

    depends_on:

      - priya

    networks:

      - redis-net

    command: ["sleep", "infinity"]
 
networks:

  redis-net:

    driver: bridge

 
